//! The generated Lexbor layout, plus the agreement checks over it.
//!
//! `build.rs` runs bindgen over the vendored headers; this module includes the
//! result and pins the facts the rest of the crate depends on. See
//! notes/rust_port_remaining.ja.md step 5 for why generated rather than
//! hand-written, and for what this does not remove.

#![allow(unsafe_code)]

/// The generated bindings, with the blanket allows scoped to THEM.
///
/// They were on the whole module, which meant the hand-written parts below -
/// `consts`, the agreement checks - were also exempt from dead-code and naming
/// lints they should not be.
mod sys {
    #![allow(
        non_camel_case_types,
        non_snake_case,
        non_upper_case_globals,
        dead_code
    )]
    include!(concat!(env!("OUT_DIR"), "/lexbor_sys.rs"));
}

pub use sys::*;

/// An HTML parser, destroyed however its scope exits.
///
/// Lexbor's `parser_destroy` unrefs the tokenizer and the tree and NOTHING
/// else: the document a parse produced outlives it, which is what lets a parse
/// hand its document back. Both parse paths - the tracked document parse and
/// the fragment parser - own theirs through this type, so a path added later
/// cannot forget the destroy the way three hand-written ones could.
pub struct HtmlParser(core::ptr::NonNull<lxb_html_parser_t>);

impl HtmlParser {
    /// A created and initialised parser, or `None` if either step failed (a
    /// half-built one is destroyed here rather than handed out).
    pub fn create() -> Option<HtmlParser> {
        // SAFETY: the constructor pair Lexbor documents; `init` is called on
        // exactly what `create` returned.
        unsafe {
            let p = core::ptr::NonNull::new(lxb_html_parser_create())?;
            let this = HtmlParser(p);
            if lxb_html_parser_init(p.as_ptr()) != consts::STATUS_OK {
                return None; /* `this` drops, destroying it */
            }
            Some(this)
        }
    }

    #[inline]
    pub fn as_ptr(&self) -> *mut lxb_html_parser_t {
        self.0.as_ptr()
    }
}

impl Drop for HtmlParser {
    fn drop(&mut self) {
        // SAFETY: this type owns the parser, and nothing else destroys it.
        unsafe { lxb_html_parser_destroy(self.0.as_ptr()) };
    }
}

/// The document a fragment parse builds its nodes in, destroyed however its
/// scope exits.
///
/// `lxb_html_parse_fragment` puts the fragment in a document of its own that
/// destroying the parser does not free - one leaked per `inner_html=` before it
/// was freed by hand. The nodes a caller keeps are imported copies in its own
/// document, so this one goes as soon as the import is done.
pub struct TransientDoc(core::ptr::NonNull<lxb_html_document_t>);

impl TransientDoc {
    /// The document `node` was parsed into.
    ///
    /// # Safety
    /// `node` must be a live node whose owner document is the transient one -
    /// the root a fragment parse just returned - and must not be destroyed by
    /// anything else.
    pub unsafe fn of(node: *mut lxb_dom_node_t) -> Option<TransientDoc> {
        core::ptr::NonNull::new((*node).owner_document as *mut lxb_html_document_t)
            .map(TransientDoc)
    }
}

impl Drop for TransientDoc {
    fn drop(&mut self) {
        // SAFETY: this type owns the document, and the caller's nodes are
        // copies in its own document by the time this runs.
        unsafe { lxb_html_document_destroy(self.0.as_ptr()) };
    }
}

/* ------------------------------------------------------------------ *
 * Names                                                              *
 * ------------------------------------------------------------------ */

/* The DOM handle types, under the short names the rest of the crate uses. The
 * generated `lxb_dom_*_t` spellings stay available; these exist so a cast at a
 * call site reads as a cast to a Lexbor node rather than to a bindgen name. */
pub type LxbNode = lxb_dom_node_t;
pub type LxbElement = lxb_dom_element_t;
pub type LxbAttr = lxb_dom_attr_t;
pub type LxbDoc = lxb_dom_document_t;

/* ------------------------------------------------------------------ *
 * Header-less exports                                                *
 * ------------------------------------------------------------------ */

/* Every other Lexbor function the crate calls - the `_noi` twins of the
 * `lxb_inline` accessors included - is GENERATED by build.rs from the header
 * that declares it, so its signature is Lexbor's own and a change to it fails
 * the build. These three are the exception: exported by Lexbor but declared
 * in NO header, so bindgen cannot see them. Lexbor's own sources
 * forward-declare them exactly this way. What stands in for the header is
 * build.rs's `UNDECLARED_EXPORTS`, which reads each C DEFINITION and fails the
 * build if it no longer matches what is written here.
 *
 * `lxb_ns_append` interns a namespace URI in the document's table.
 * `lxb_dom_attr_set_name_ns` names an attribute from (namespace, qualified
 * name), splitting prefix/local and interning the namespace.
 * `lxb_dom_attr_qualified_name_append` interns a name CASE-PRESERVING, which is
 * what lets createDocumentType keep its case where Lexbor's own create()
 * lowercases. */
extern "C" {
    pub fn lxb_ns_append(
        hash: *mut core::ffi::c_void,
        link: *const u8,
        length: usize,
    ) -> *const LxbNsData;
    pub fn lxb_dom_attr_set_name_ns(
        attr: *mut LxbAttr,
        link: *const u8,
        link_length: usize,
        name: *const u8,
        name_length: usize,
        to_lowercase: bool,
    ) -> u32;
    pub fn lxb_dom_attr_qualified_name_append(
        hash: *mut core::ffi::c_void,
        name: *const u8,
        length: usize,
    ) -> *mut LxbAttrData;
}

/// `lxb_ns_data_t`, of which only `ns_id` is read. It is `lexbor_hash_entry_t
/// entry; lxb_ns_id_t ns_id; ...`, and the entry's layout is Lexbor's business -
/// so the id is reached through the generated struct rather than guessed at.
pub type LxbNsData = lxb_ns_data_t;

/// `lxb_dom_attr_data_t`, likewise read only for `attr_id`.
pub type LxbAttrData = lxb_dom_attr_data_t;

/// bindgen names an enum's constants by whether the enum is NAMED: a typedef'd
/// one gets its type as a prefix (`lxb_ns_id_enum_t_LXB_NS_HTML`), a truly
/// anonymous one keeps the bare name (`LXB_CSS_AT_RULE_MEDIA`). That is an
/// artefact of the headers, not something callers should have to know, so the
/// aliases below give every constant the name it has in C.
pub mod consts {
    /// Rule kinds (`lxb_css_rule_type_t`).
    pub const CSS_RULE_STYLE: usize = super::lxb_css_rule_type_t_LXB_CSS_RULE_STYLE as usize;
    pub const CSS_RULE_AT_RULE: usize = super::lxb_css_rule_type_t_LXB_CSS_RULE_AT_RULE as usize;
    pub const CSS_RULE_BAD_STYLE: usize =
        super::lxb_css_rule_type_t_LXB_CSS_RULE_BAD_STYLE as usize;
    pub const CSS_RULE_DECLARATION: usize =
        super::lxb_css_rule_type_t_LXB_CSS_RULE_DECLARATION as usize;

    /// At-rule kinds (an anonymous enum, hence the bare generated names).
    pub const AT_RULE_UNDEF: usize = super::LXB_CSS_AT_RULE__UNDEF as usize;
    pub const AT_RULE_CUSTOM: usize = super::LXB_CSS_AT_RULE__CUSTOM as usize;
    pub const AT_RULE_FONT_FACE: usize = super::LXB_CSS_AT_RULE_FONT_FACE as usize;
    pub const AT_RULE_MEDIA: usize = super::LXB_CSS_AT_RULE_MEDIA as usize;
    pub const AT_RULE_NAMESPACE: usize = super::LXB_CSS_AT_RULE_NAMESPACE as usize;

    /// Status codes (`lexbor_status_t`) - every Lexbor entry point returns one.
    ///
    /// Only `OK` and `ERROR` are given a value in the header; the rest are
    /// positional, so a member inserted upstream renumbers them all. Hence
    /// generated rather than written out: `STATUS_STOP` was transcribed as
    /// `0x0013`, which is 19, which is what it happens to be today.
    pub const STATUS_OK: u32 = super::lexbor_status_t_LXB_STATUS_OK;
    pub const STATUS_ERROR: u32 = super::lexbor_status_t_LXB_STATUS_ERROR;
    pub const STATUS_ERROR_MEMORY_ALLOCATION: u32 =
        super::lexbor_status_t_LXB_STATUS_ERROR_MEMORY_ALLOCATION;
    /// Returned by a traversal callback to end the walk early.
    pub const STATUS_STOP: u32 = super::lexbor_status_t_LXB_STATUS_STOP;
}

/* ------------------------------------------------------------------ *
 * The CSS selector parser                                            *
 * ------------------------------------------------------------------ */

/* The parser is generated OPAQUE (build.rs): nothing reads a field of it. The
 * short names are what `css_engine` and its users spell. */

/// `lxb_css_parser_t`.
pub type CssParser = lxb_css_parser_t;
/// `lxb_css_memory_t`.
pub type CssMemory = lxb_css_memory_t;
/// `lxb_css_selectors_t`.
pub type CssSelectors = lxb_css_selectors_t;
